name: sirelle
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  rive: ^0.12.4
  image_picker: ^1.0.7
  country_picker: ^2.0.21
  shimmer: ^3.0.0
  shared_preferences: ^2.2.2
  confetti: ^0.8.0
  intl: ^0.20.2
  google_fonts: ^6.2.0
  marquee: ^2.2.3
  lottie: ^3.1.0
  country_icons: ^3.0.0   # or whatever version you use
  sqflite: ^2.3.3
  path: ^1.9.0
  cupertino_icons: ^1.0.8
  

  # Add these packages for OpenAI support
  http: ^1.1.0
  dart_openai: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^6.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/logo/
    - assets/splash/
    - assets/animation/
    - assets/icons/
    - assets/stamp/

    - assets/images/bottles/b1/
    - assets/images/bottles/b2/
    - assets/images/bottles/b3/
    - assets/images/bottles/b4/
    - assets/images/bottles/b5/   
    - assets/images/bottles/b6/
    - assets/images/bottles/b7/
    - assets/images/bottles/b8/

    - assets/images/candle/c1/
    - assets/images/candle/c2/
    - assets/images/candle/c3/
    - assets/images/candle/c4/      
    - assets/images/candle/c5/
    - assets/images/candle/c6/  
    - assets/images/candle/c7/
    - assets/images/candle/c8/
    - assets/images/candle/c9/
    - assets/images/candle/c10/
    - assets/images/candle/c11/
    - assets/images/candle/c12/
    - assets/images/candle/c13/
    - assets/images/candle/c14/
    - assets/images/candle/c15/
    - assets/images/candle/c16/
    - assets/images/candle/c17/
    - assets/images/candle/c18/
    - assets/images/candle/c19/
    - assets/images/candle/c20/
    - assets/images/candle/c21/
    - assets/images/candle/c22/
    - assets/images/candle/c23/    

    - assets/images/caps/ca1/
    - assets/images/caps/ca2/
    - assets/images/caps/ca3/
    - assets/images/caps/ca4/
    - assets/images/caps/ca5/
    - assets/images/caps/ca6/
    - assets/images/caps/ca7/
    - assets/images/caps/ca8/

    - assets/images/ceramic/ce1/
    - assets/images/ceramic/ce2/
    - assets/images/ceramic/ce3/
    - assets/images/ceramic/ce4/
    - assets/images/ceramic/ce5/
    - assets/images/ceramic/ce6/
    - assets/images/ceramic/ce7/    
    - assets/images/ceramic/ce8/

    - assets/images/hair_accessories/h1/
    - assets/images/hair_accessories/h2/
    - assets/images/hair_accessories/h3/
    - assets/images/hair_accessories/h4/      
    - assets/images/hair_accessories/h5/
    - assets/images/hair_accessories/h6/  
    - assets/images/hair_accessories/h7/
    - assets/images/hair_accessories/h8/

    - assets/images/key_chain/k1/
    - assets/images/key_chain/k2/
    - assets/images/key_chain/k3/
    - assets/images/key_chain/k4/      
    - assets/images/key_chain/k5/
    - assets/images/key_chain/k6/  
    - assets/images/key_chain/k7/
    - assets/images/key_chain/k8/

    - assets/images/letter/1/
    - assets/images/letter/2/
    - assets/images/letter/3/
    - assets/images/letter/4/      
    - assets/images/letter/5/
    - assets/images/letter/6/  
    - assets/images/letter/7/
    - assets/images/letter/8/   
    - assets/images/letter/9/
    - assets/images/letter/10/
    - assets/images/letter/11/
    - assets/images/letter/12/
    - assets/images/letter/13/
    - assets/images/letter/14/
    - assets/images/letter/15/
    - assets/images/letter/16/
    - assets/images/letter/17/
    - assets/images/letter/18/
    - assets/images/letter/19/
    - assets/images/letter/20/    
    - assets/images/letter/21/
    - assets/images/letter/22/

    - assets/images/nails/n1/
    - assets/images/nails/n2/
    - assets/images/nails/n3/
    - assets/images/nails/n4/      
    - assets/images/nails/n5/
    - assets/images/nails/n6/  
    - assets/images/nails/n7/
    - assets/images/nails/n8/

    - assets/images/plusie/p1/
    - assets/images/plusie/p2/
    - assets/images/plusie/p3/
    - assets/images/plusie/p4/      
    - assets/images/plusie/p5/
    - assets/images/plusie/p6/  
    - assets/images/plusie/p7/
    - assets/images/plusie/p8/

    - assets/images/boy_friend/
    - assets/images/girl_friend/